### PR TITLE
Retry canonical signature

### PR DESCRIPTION
**Pull request by rubensayshi**
I ran into a non-canonical signature, can't reproduce it anymore though but I guess having something to deal with it in the code doesn't hurt ...

Also noticed there was no test for signing ... so I added one.

And there was some random test failure because I did `BitcoinLib::setMagicByteDefaults('bitcoin-testnet');` somewhere in `RawTransactionTest` so I added `BitcoinLib::setMagicByteDefaults('bitcoin');` to the `setup()` so that it will always be bitcoin unless overwritten.

### CODE REVIEW

**Comment by afk11** [comment]
I'll try have another look at this in the next day or so, I've been incredibly busy this past while :frown:

One or two tests in the is_canonical_signature function are commented, and I know they were proving awkward at the time. I suspect we can get this working, since it's probably an issue with padding or AND operations not being carried out to detect that there's an issue, instead of repeating the signing process.

**Comment by rubensayshi** [comment]
I'm not entirely sure because half the signatures were from bitcoinlib-js and the other half from BitcoinLib, but I think this error from bitcoind was because of signatures created by BitcoinLib (because I retried feeding the same partially-signed hex to the PHP part of the system and the 2nd time it succeeded):
```
2015-01-14 15:58:46 ERROR: Non-canonical signature: R value excessively padded
2015-01-14 15:58:46 ERROR: Non-canonical signature: R value excessively padded
```

**Comment by afk11** [comment]
Ok I had a go at this. https://github.com/Bit-Wasp/bitcoin-lib-php/compare/fixCheckCanonicalSignature?expand=1#diff-c87fe9e3825f612fc0cdf8dc090676e9R316 Rewrote is_canonical_signature() and encode_signature() and have tests for canonical signatures, and also signatures which fail for a specific reason (taken from the Satoshi client)

I also have a loop where 100 sigs are generated, serialized, and checked by is_canonical_check(). 

It's possible that the encoding function was incorrect, as it was doing str_pad() to pad it to 64 characters. is_canonical_signature() wasn't checking that either, so there was no way for it to ever catch it.

Let me know how this goes!

**Comment by rubensayshi** [comment]
okay, dropping this PR in favor of your work

**Pull request closed without merging**
