### PR TITLE
add new deriveAddressFromSignature function

### PR DESCRIPTION
**Pull request by cryptonaut420**
I added in this method which returns the public BTC address used to sign a particular message, using only signature+message as parameters. Using this for a "sign in with verified bitcoin address" feature on a project

### CODE REVIEW

**Comment by afk11** [comment]
Nice job, seems reasonable to extract this as a separate method. Before I merge, maybe refactor `verifyMessage` so it uses the new function, since much of the code is duplicated there as well!

**Comment by afk11** [comment]
Tests are bailing due to the codestyle. If you run this it will sort all of that out!

`./vendor/bin/phpcbf --standard=./build/phpcs.xml -n -a ./src/`

**Comment by cryptonaut420** [comment]
thanks! updated code, how's it look now?

**Comment by afk11** [comment]
Sorry for the delay, looks good to me!

**Pull request merged**
