### PR TITLE
Fixed RawTransaction::decode returned txid

### PR DESCRIPTION
**Pull request by willgriffin**
bytes weren't being flipped 

<3

### CODE REVIEW

**Comment by rubensayshi** [comment]
hmm, `txid` is something different than the `txhash`, there's `RawTransaction::hash_from_txid` and `RawTransaction::hash_from_raw` to get the hash instead of the txid.

we could potentially add 'txhash' to the `RawTransaction::decode` output, but `txid` should remain what it is now.

**Comment by willgriffin** [comment]
the 'txid' returned after this patch matches the 'txid' returned by the default rpc, i'm a bit confused as to why this wouldn't be the desired behaviour?

**Comment by rubensayshi** [comment]
I'm sorry, 

 - the `hash256` of a transaction is what it used when encoding a transaction and sending it across the network
 - for w/e weird ass reason we however flip the bytes of the `hash256` and call that the `txid` whenever it's comunicated to a human (wallets, blockexplorers, APIs, etc)

since we're following this principal and when you `::decode` we show the `txid`s of the inputs, the `txid` for the transaction itself should be `txid` too, while it is the `hash` atm.

**Comment by willgriffin** [comment]
Exactly what this patch rectify's :)

**Comment by rubensayshi** [comment]
yea, I did a small PR ontop of yours on your repo to clean up a few places that might otherwise be confusing; https://github.com/willgriffin/bitcoin-lib-php/pull/1

@afk11 is the lead maintainer of this library and he's currently on vacation, so it's gonna take a few days before this can get merged.  
It also requires a major version bump because it breaks BC.

**Comment by willgriffin** [comment]
Hrm .. well if a major version bump is coming I guess I might as well mention for your consideration another area in which the output differs from the default rpc is that in the decoded transaction vout array the index property is named 'vout' (which matches the vin array) where the rpc uses 'n' for the vout array. I don't know how big of a deal that is, just something I had to patch around. To be fully compatible with the rpc the values would have to be returned in BTC and that would suck as a singular option

**Comment by rubensayshi** [comment]
I'm not entirely sure if BitcoinLib was ment to be compatible with the RPC entirely, it's very close though so I think @afk11 originally ment to make it compatible so we might as well change it.

I guess we should add a section to the README with CHANGELOG and BC breaks between versions.

**Comment by willgriffin** [comment]
I concur it's best to be as compatible as possible but at the same time it's kinda mean to break shit on peeps. It's probably most kind to introduce a compatibility flag and ease in any dependent projects.  I've come across these distinctions while incorporating the library into my fork of nbobtc/bitcoin-php of which my current project is dependent upon so inconsistencies are prevalent immediately. When/if i submit those pull requests and nbotc thinks they're of value, people will have that option if strict/'drop in' compatibility is the goal. Personally it pains me a bit knowing floats are being converted to integers and back wasting cycles , so a compatibility flag would be hella sweet but i can see it being needless bloat at the same time as the original rpc spec kinda sucks

**Comment by rubensayshi** [comment]
"Personally it pains me a bit knowing floats are being converted to integers and back wasting cycles"  
who? what? where? I don't quite follow

Anyway, the RPC indeed isn't really that great to follow, but since we're really close in matching the output, we might as well match it ...

@afk11 is working on a complete OOP rewrite (from scratch) btw; github.com/afk11/bitcoin  
figured you might be interested in such a project since having objects instead of arrays is a lot better imo.  
still a work in progress though

**Comment by willgriffin** [comment]
In my nbobtc/bitcoind fork incorporating functions from this library i convert from satoshi to float to maintain drop in compatiblity and then in my project convert back to satoshi to maintain sanity ;)

**Comment by afk11** [comment]
Hey @willgriffin thanks for the PR, yeah generally most of the functions here should match the RPC, probably best to go all out. 

I'm guessing in your situation extra stuff isn't a big problem (some of the output in sign() isn't provided by the RPC) but let me know if there are any other places the output is inconsistent!

**Comment by willgriffin** [comment]
Will do, thanks!

**Pull request merged**
