### PR TITLE
Float rounding error

### PR DESCRIPTION
**Pull request by rubensayshi**
To be honest, I'd strongly prefer if RawTransaction would only accept and return integers, but this at least avoids the rounding error that is possible now (see first commit with test added that fails)

### CODE REVIEW

**Comment by rubensayshi** [comment]
@afk11 @btcdrak we should either merge this since we actually have float rounding errors in the code right now or break backwards compatability and stop accepting floats and only accept integers, in which case we make it the 'users' problem instead of ours. 

either way I think providing some helpers to convert from BTC to satoshi and back is not a bad idea either.

if we're gonna break BC for the sorting thing then we might as well change to only accepting integers too ... 
also if we add `is_int` checks then at least we can throw an Exception if someone tries to feed it a float

**Comment by rubensayshi** [comment]
@afk11 @btcdrak are you in favor of me doing a PR to no longer accept floats and only ints and bump major version because of BC breaking?

I'm currently using a forked package `blocktrail/bitcoinlib-php` because we have these open PRs so I'd like to get the PRs merged / closed, plus the current version of bitcoinlib-php has these float rounding issues which we should get rid of regardless of my desires ...

**Comment by afk11** [comment]
Know it was discussed elsewhere, I'm in favor of this since it's been shown that the problem arises at fairly typical amounts..

**Comment by rubensayshi** [comment]
closed, in favor of https://github.com/Bit-Wasp/bitcoin-lib-php/pull/58

**Pull request closed without merging**
